[project]
name = "arrayshow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=8.32.0",
    "matplotlib>=3.10.0",
    "numpy>=2.2.2",
    "pyqt5>=5.15.11",
]

[tool.setuptools]
packages = ["arrayshow"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
