[project]
name = "arrayshow"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Oscar van der Heide", email = "oscarvanderheide@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "nibabel>=5.3.2",
    "numpy>=2.3.0",
    "pyqt5>=5.15.11",
    "qmricolors",
    "vispy>=0.15.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
qmricolors = { git = "https://github.com/oscarvanderheide/qmricolors.git" }
